# Language parsing definitions

# To add a new language you can follow this template:
# [languages.$EXT]  --- Replace $EXT with whatever the language's file extension is 
# name = ""         --- The full name of the language
# inline = ""       --- whatever denotes the start of an inline comment
# blockstart = ""   --- whatever denotes the start of a block comment
# blockend = ""     --- whatever denotes the end of a block comment

# If you add support for a language, please submit a pull request
# to https://github.com/Pax-Newman/ToView with your changes

[languages]

[languages.py]
name = "Python"
inline = "#"
blockstart = ""
blockend = ""

[languages.go]
name = "Go"
inline = "//"
blockstart = ""
blockend = ""